### ISSUE TITLE
license need

### ISSUE THREAD

**Issue by GazeLei** [svip-lab/RGBD-Gaze#1]
Hi SVIP-Lab,

could you add license to your dataset on the OneDrive?
due to the Ethics issue, i cannot use your datasets without license and ethics approval from uni.

best

**Comment by iszff** [comment]
Hi，
1.when I run trainer_aaai.py，I meet this problem
Traceback (most recent call last):
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py", line 602, in <module>
    trainer.train_headpose(10, lr=2e-1)
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py", line 143, in train_headpose
    self._train_headpose_epoch()
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py", line 422, in _train_headpose_epoch
    for i, batch in enumerate(self.temps.train_loader):
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/data/gaze_dataset.py", line 58, in __getitem__
    le_coor = np.load(self.le_coord_list[idx])
AttributeError: 'GazePointAllDataset' object has no attribute 'le_coord_list'.

2.If I uncomment line 38th  and 39th in gaze_dataset.py,this problem occurs
    38    #self.le_coord_list = (root_dir + "/" + self.anno["left_eye_coord"]).tolist()
    39    #self.re_coord_list = (root_dir + "/" + self.anno["right_eye_coord"]).tolist()
$ /home/workspace/feifeizhang/anconda/bin/python /home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py
<GazeTrainer.train_headpose:INFO> preparing for headpose training loop.
Traceback (most recent call last):
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'left_eye_coord'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py", line 602, in <module>
    trainer.train_headpose(10, lr=2e-1)
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py", line 128, in train_headpose
    self.temps.train_loader = self._get_trainloader()
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/trainer_aaai.py", line 201, in _get_trainloader
    info=True, eye_bbox=True, face_bbox=True, eye_coord=True)
  File "/home/workspace/feifeizhang/GAZE/RGBD-Gaze-master/code/data/gaze_dataset.py", line 38, in __init__
    self.le_coord_list = (root_dir + "/" + self.anno["left_eye_coord"]).tolist()
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/workspace/feifeizhang/anconda/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'left_eye_coord'
3.
I checked the file ”train_meta.csv“ in the data set and found that there is no such item ”left_eye_coord“、”right_eye_coord“.
